settings:
  title: 'NemG Status'
  url: 'https://status.nemg.workers.dev'           # Dùng cho các thông báo (Slack, Discord)
  logo: logo-192x192.png                          # Logo nằm trong thư mục ./public/
  daysInHistogram: 90                             # Số ngày hiển thị trong biểu đồ
  collectResponseTimes: true                      # Thu thập thời gian phản hồi trung bình từ các vị trí CRON

  # Thông điệp trạng thái hệ thống
  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'

  # Nhãn trạng thái của từng monitor
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'

  # Nhãn hiển thị cho từng ngày trong biểu đồ
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)'     # VD: "2 incident(s) recorded"

monitors:
  - id: nemg.me                    # ID duy nhất, viết liền-không-dấu
    name: nemg.me
    description: 'Profile NemG.'
    url: 'https://nemg.me/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200
